# Border Pair Tracing Algorithm

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### OR Gate

In [ ]:
dat = pd.read_csv('or_data.csv')
X = pd.DataFrame(dat, columns=['A', 'B']).to_numpy()
Y = pd.DataFrame(dat, columns=['Y']).to_numpy()

In [ ]:
Y

array([[0],
       [1],
       [1],
       [1]])

## Calculating the euclidean distance

In [ ]:
m = X.shape[0]
dist = np.zeros((m,m))
dist[0]

array([0., 0., 0., 0.])

In [ ]:
for i in range(m):
  for j in range(m):
    dist[i,j] = np.linalg.norm(X[i]-X[j])


dist

array([[0.        , 1.        , 1.        , 1.41421356],
       [1.        , 0.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 0.        , 1.        ],
       [1.41421356, 1.        , 1.        , 0.        ]])

In [ ]:
dist[0,:]

array([0.        , 1.        , 1.        , 1.41421356])

In [ ]:
dist[:,1]

array([1.        , 0.        , 1.41421356, 1.        ])

In [ ]:
for i in range(m):
  for j in range(m):
    if i != j and i < j and Y[i] != Y[j]:
      row = dist[i,:]
      column = dist[:,j]
      if dist[i,j] == np.min(row[np.nonzero(row)]) and dist[i,j] == np.min(column[np.nonzero(column)]):
        print(" {} and {} are border pairs".format(i,j) )

 0 and 1 are border pairs
 0 and 2 are border pairs
